/*
 * SHATU: SHA-256 Tutor
 * 
 *  (C) Johanna & Richard Blumenthal, All rights reserved
 * 
 *  Unauthorized use, duplication or distribution without the authors'
 *  permission is strictly prohibited.
 * 
 *  Unless required by applicable law or agreed to in writing, this
 *  software is distributed on an "AS IS" basis without warranties
 *  or conditions of any kind, either expressed or implied.
 */
package edu.regis.shatu.dao;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.GregorianCalendar;

import edu.regis.shatu.dao.interfaces.CRUD;
import edu.regis.shatu.err.InconsistentDBException;
import edu.regis.shatu.err.NonRecoverableException;
import edu.regis.shatu.err.ObjDuplicateException;
import edu.regis.shatu.err.ObjNotFoundException;
import edu.regis.shatu.model.Account;
import edu.regis.shatu.model.CourseDigest;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.Task;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.UnitDigest;
import edu.regis.shatu.model.aol.PendingStep;
import edu.regis.shatu.model.aol.PendingTask;
import edu.regis.shatu.svc.CourseSvc;
import edu.regis.shatu.svc.ServiceFactory;
import edu.regis.shatu.svc.SessionSvc;

/**
 *
 * A Data Access Object implementing tutoring {@link SessionSvc} behaviors.
 * 
 * @author rickb
 */
public class SessionDAO extends MySqlDAO implements SessionSvc, CRUD<TutoringSession> {

    public SessionDAO() {
        super("TutoringSession", "Id");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void create(TutoringSession session) throws ObjDuplicateException, NonRecoverableException {
        final String sql = "INSERT INTO TutoringSession (UserId, SecurityToken, IsActive, StartDate, CourseId, UnitId) VALUES (?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (exists("UserId", userId))
                throw new ObjDuplicateException("Tutoring session exists " + userId);

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, 0); // Start with Unit 0

            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));

                createPendingTasks(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);

        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TutoringSession retrieve(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "SELECT Id,SecurityToken,IsActive,StartDate,CourseId,UnitId FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            // I don't like this at all.
            // Just don't know how else to return a tutoring session when you need a
            // Student object to make a TutoringSession, but then in turn need an Account
            // object to make a student.
            AccountDAO accDao = new AccountDAO();
            Account acc = accDao.retrieve(userId);
            Student stu = new Student(acc);

            if (rs.next()) {
                TutoringSession session = new TutoringSession(stu);
                session.setId(rs.getInt(1));
                session.setSecurityToken(rs.getString(2));
                session.setIsActive(rs.getBoolean(3));

                Timestamp timestamp = rs.getTimestamp(4);
                GregorianCalendar calendar = new GregorianCalendar();
                calendar.setTimeInMillis(timestamp.getTime());
                session.setStartDate(calendar);

                int courseId = rs.getInt(5);
                int unitId = rs.getInt(6);

                CourseSvc courseSvc = ServiceFactory.findCourseSvc();
                try {
                    CourseDigest digest = courseSvc.retrieveDigest(courseId, conn);
                    session.setCourse(digest);
                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-2 Course digest not found for courseId " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                try {
                    UnitDigest unitDigest = courseSvc.retrieveUnitDigest(courseId, unitId, conn);
                    session.setUnit(unitDigest);

                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-3 Unit " + unitId + " not found in course " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                session.setTasks(retrievePendingTasks(session, conn));

                return session;

            } else {
                throw new ObjNotFoundException("Session not found for userId:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-4" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String retrieveSecurityToken(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "SELECT SecurityToken FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getString(1);

            } else {
                throw new ObjNotFoundException("User Id:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-5" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     * 
     * 1. Rename existing session file
     * 2. Create a new session file using the given update
     * 3. Delete the original, but now renamed file.
     */
    @Override
    public void update(TutoringSession session) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "INSERT INTO TutoringSession (UserId, SecurityToken, IsActive, StartDate, CourseId, UnitId) VALUES (?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (!exists("UserId", userId))
                throw new ObjNotFoundException("No TutoringSession matching " + userId + " found.");

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, 0); // Start with Unit 0

            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));

                createPendingTasks(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);

        } finally {
            close(conn, stmt);
        }
    }

    /**
     * Utility that deletes the given a file.
     * 
     * @param file a File with an absolute path to delete.
     */
    private void delete(File file) {
        if (file.exists())
            file.delete();
    }

    private void createPendingTasks(TutoringSession session, Connection conn)
            throws NonRecoverableException {
        final String sql = "INSERT INTO PendingTask (SessionId, TaskId, PendingStepId) VALUES (?,?,?)";

        int sessionId = session.getId();

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            for (PendingTask pTask : session.getTasks()) {
                stmt.setInt(1, sessionId);
                stmt.setInt(2, pTask.getTask().getId());
                PendingStep pStep = pTask.currentStep();

                int pId = createPendingStep(sessionId, pStep, conn);
                stmt.setInt(3, pId);

                stmt.executeUpdate();

            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-7", e);

        } finally {
            close(stmt);
        }
    }

    private int createPendingStep(int sessionId, PendingStep pStep, Connection conn)
            throws NonRecoverableException {
        final String sql = "INSERT INTO PendingStep (SessionId, StepId, NotifyTutor, IsCompleted, CurrentHintIndex) VALUES (?,?,?,?,?)";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setInt(1, sessionId);
            stmt.setInt(2, pStep.getStep().getId());
            stmt.setBoolean(3, pStep.isNotifyTutor());
            stmt.setBoolean(4, pStep.isCompleted());
            stmt.setInt(5, pStep.getCurrentHintIndex());

            stmt.executeUpdate();

            ResultSet rs = stmt.getGeneratedKeys();

            if (rs.next()) {
                int pId = rs.getInt(1);
                pStep.setId(pId);
                return pId;
            } else {
                throw new NonRecoverableException("SessionDAO-ERR-8: PendingStep AutoIncrement Failed");
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-9", e);

        } finally {
            close(stmt);
        }
    }

    private ArrayList<PendingTask> retrievePendingTasks(TutoringSession session, Connection conn)
            throws NonRecoverableException {

        final String sql = "SELECT TaskId, PendingStepId FROM PendingTask WHERE SessionId = ?";

        ArrayList<PendingTask> pendingTasks = new ArrayList<>();

        PreparedStatement stmt = null;

        int sessionId = session.getId();

        int taskId = -1;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, sessionId);

            ResultSet rs = stmt.executeQuery();

            CourseSvc courseSvc = ServiceFactory.findCourseSvc();

            while (rs.next()) {
                taskId = rs.getInt(1);

                Task task = courseSvc.retrieveTask(session.getCourse().getId(), taskId, conn);

                PendingTask pTask = new PendingTask(task);

                PendingStep pStep = retrievePendingStep(rs.getInt(2), sessionId, task, conn);

                pTask.setCurrentStep(pStep);

                pendingTasks.add(pTask);
            }

            return pendingTasks;

        } catch (ObjNotFoundException ex) {
            String errMsg = "Task not found in pending task" + taskId;
            throw new NonRecoverableException("SessionDAO-ERR-10", new InconsistentDBException(errMsg));
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-11", e);

        } finally {
            close(stmt);
        }
    }

    public PendingStep retrievePendingStep(int pendingStepId, int sessionId, Task task, Connection conn)
            throws NonRecoverableException {

        final String sql = "SELECT StepId, NotifyTutor, IsCompleted, CurrentHintIndex FROM PendingStep WHERE Id = ?";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, pendingStepId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                PendingStep pStep = new PendingStep(task.findStepById(rs.getInt(1)));

                pStep.setNotifyTutor(rs.getBoolean(2));
                pStep.setIsCompleted(rs.getBoolean(3));

                return pStep;
            } else {
                String errMsg = "PendingStep not found in pending task" + pendingStepId;
                throw new NonRecoverableException("SessionDAO-ERR-12", new InconsistentDBException(errMsg));
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-13", e);

        } finally {
            close(stmt);
        }
    }

}
