/*
 * SHATU: SHA-256 Tutor
 * 
 *  (C) Johanna & Richard Blumenthal, All rights reserved
 * 
 *  Unauthorized use, duplication or distribution without the authors'
 *  permission is strictly prohibited.
 * 
 *  Unless required by applicable law or agreed to in writing, this
 *  software is distributed on an "AS IS" basis without warranties
 *  or conditions of any kind, either expressed or implied.
 */
package edu.regis.shatu.dao;

import static edu.regis.shatu.dao.MySqlDAO.URL;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.GregorianCalendar;

import edu.regis.shatu.dao.interfaces.CRUD;
import edu.regis.shatu.err.InconsistentDBException;
import edu.regis.shatu.err.NonRecoverableException;
import edu.regis.shatu.err.ObjDuplicateException;
import edu.regis.shatu.err.ObjNotFoundException;
import edu.regis.shatu.model.Account;
import edu.regis.shatu.model.CourseDigest;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.Task;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.UnitDigest;
import edu.regis.shatu.model.aol.PendingStep;
import edu.regis.shatu.model.aol.PendingTask;
import edu.regis.shatu.model.aol.StudentModel;
import edu.regis.shatu.svc.CourseSvc;
import edu.regis.shatu.svc.ProblemSvc;
import edu.regis.shatu.svc.ServiceFactory;
import edu.regis.shatu.svc.SessionSvc;
import edu.regis.shatu.svc.StudentModelSvc;

/**
 *
 * A Data Access Object implementing tutoring {@link SessionSvc} behaviors.
 * 
 * @author rickb
 */
public class SessionDAO extends MySqlDAO implements SessionSvc, CRUD<TutoringSession> {

    public SessionDAO() {
        super("TutoringSession", "Id");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void create(TutoringSession session) throws ObjDuplicateException, NonRecoverableException {
        final String sql = "INSERT INTO TutoringSession " + 
                "(UserId, SecurityToken, IsActive, StartDate, CourseId, UnitId, ProblemId) " + 
                "VALUES (?,?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (exists("UserId", userId))
                throw new ObjDuplicateException("Tutoring session exists " + userId);

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, 0); // Start with Unit 0
            stmt.setInt(7, session.getProblem().getId());
            
            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));
                createPendingTasks(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);
        } finally {
            System.out.println("session id after insert = " + session.getId());
            System.out.println("session task count = " + session.getTasks().size());
            System.out.println("problem task count = " + session.getProblem().getTasks().size());
            close(conn, stmt);
        }
    }
    
    @Override
    public TutoringSession retrieve(Account account) throws ObjNotFoundException, NonRecoverableException {
               final String sql =
                "SELECT Id, SecurityToken, IsActive, StartDate, CourseId, UnitId, ProblemId FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;
        
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            Student student = new Student(account);

            if (rs.next()) {
                TutoringSession session = new TutoringSession(student);
                session.setId(rs.getInt(1));
                session.setSecurityToken(rs.getString("SecurityToken"));
                session.setIsActive(rs.getBoolean("IsActive"));

                Timestamp timestamp = rs.getTimestamp("StartDate");
                GregorianCalendar calendar = new GregorianCalendar();
                calendar.setTimeInMillis(timestamp.getTime());
                session.setStartDate(calendar);
                
                StudentModelSvc stuModSvc = ServiceFactory.findStudentModelSvc();
                StudentModel studentModel = stuModSvc.retrieve(userId);
                student.setStudentModel(studentModel);

                int courseId = rs.getInt("CourseId");
                int unitId = rs.getInt("UnitId");

                CourseSvc courseSvc = ServiceFactory.findCourseSvc();
                try {
                    CourseDigest digest = courseSvc.retrieveDigest(courseId, conn);
                    session.setCourse(digest);
                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-2 Course digest not found for courseId " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                try {
                    UnitDigest unitDigest = courseSvc.retrieveUnitDigest(courseId, unitId, conn);
                    session.setUnit(unitDigest);

                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-3 Unit " + unitId + " not found in course " + courseId;
                    throw new NonRecoverableException(errMsg);
                }
                
                // Fetch the problem from the DB, if one exists for the session
                ProblemSvc problemSvc = ServiceFactory.findProblemSvc();
                int problemId = rs.getInt("ProblemId");
                if (rs.wasNull()) {
                    session.setProblem(null);
                }
                else {
                    session.setProblem(problemSvc.retrieve(problemId));
                }

                session.setTasks(retrievePendingTasks(session, conn));

                return session;

            } else {
                throw new ObjNotFoundException("Session not found for userId:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-4" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TutoringSession retrieve(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql =
                "SELECT Id, SecurityToken, IsActive, StartDate, CourseId, UnitId, ProblemId FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            // ToDo: I don't like this at all.
            // Just don't know how else to return a tutoring session when you need a
            // Student object to make a TutoringSession, but then in turn need an Account
            // object to make a student.
            AccountDAO accDao = new AccountDAO();
            Account acc = accDao.retrieve(userId);
            Student student = new Student(acc);

            if (rs.next()) {
                TutoringSession session = new TutoringSession(student);
                session.setId(rs.getInt(1));
                session.setSecurityToken(rs.getString("SecurityToken"));
                session.setIsActive(rs.getBoolean("IsActive"));

                Timestamp timestamp = rs.getTimestamp("StartDate");
                GregorianCalendar calendar = new GregorianCalendar();
                calendar.setTimeInMillis(timestamp.getTime());
                session.setStartDate(calendar);
                
                StudentModelSvc stuModSvc = ServiceFactory.findStudentModelSvc();
                StudentModel studentModel = stuModSvc.retrieve(userId);
                student.setStudentModel(studentModel);

                int courseId = rs.getInt("CourseId");
                int unitId = rs.getInt("UnitId");

                CourseSvc courseSvc = ServiceFactory.findCourseSvc();
                try {
                    CourseDigest digest = courseSvc.retrieveDigest(courseId, conn);
                    session.setCourse(digest);
                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-2 Course digest not found for courseId " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                try {
                    UnitDigest unitDigest = courseSvc.retrieveUnitDigest(courseId, unitId, conn);
                    session.setUnit(unitDigest);

                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-3 Unit " + unitId + " not found in course " + courseId;
                    throw new NonRecoverableException(errMsg);
                }
                
                // Fetch the problem from the DB, if one exists for the session
                ProblemSvc problemSvc = ServiceFactory.findProblemSvc();
                int problemId = rs.getInt("ProblemId");
                if (rs.wasNull()) {
                    session.setProblem(null);
                }
                else {
                    session.setProblem(problemSvc.retrieve(problemId));
                }

                session.setTasks(retrievePendingTasks(session, conn));

                return session;

            } else {
                throw new ObjNotFoundException("Session not found for userId:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-4" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String retrieveSecurityToken(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "SELECT SecurityToken FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getString(1);
            } else {
                throw new ObjNotFoundException("User Id:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-5" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     * 
     * Updates the existing session in the database records.
     */
    @Override
    public void update(TutoringSession session) throws ObjNotFoundException, NonRecoverableException {
        //final String sql = 
        //        "INSERT INTO TutoringSession " +
        //        "(UserId, SecurityToken, IsActive, StartDate, CourseId, UnitId) " +
        //        "VALUES (?,?,?,?,?,?)";
        
        // SHAT-362: Change syntax to SQL update instead of insert.
        final String sql = 
                "UPDATE TutoringSession " +
                "SET SecurityToken=?, IsActive=?, StartDate=?, CourseId=?, UnitId=? " +
                "WHERE UserId=?";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (!exists("UserId", userId))
                throw new ObjNotFoundException("No TutoringSession matching " + userId + " found.");

	    // SHAT-362: Only need to use the sql connection.
            stmt = conn.prepareStatement(sql);

	    // SHAT-362: Adjusted ordering.
	    //stmt.setString(1, userId);
            //stmt.setString(2, session.getSecurityToken());
            //stmt.setBoolean(3, session.isActive());
            //stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            //stmt.setInt(5, session.getCourse().getId());
            //stmt.setInt(6, 0); // Start with Unit 0

	    // SHAT-362: Update SQL statement ordering.
	    stmt.setString(1, session.getSecurityToken());
	    stmt.setBoolean(2, session.isActive());
	    stmt.setTimestamp(3, new Timestamp(session.getStartDate().getTimeInMillis()));
	    stmt.setInt(4, session.getCourse().getId());
	    stmt.setInt(5, session.getUnit().getId());
	    stmt.setString(6, userId);
	    

            stmt.executeUpdate();

	    // SHAT-362: Removed as not needed for UPDATE.
            // Get the id/key autogenerated by the DB
            //ResultSet rs = stmt.getGeneratedKeys();
            //if (rs.next()) {
            //    session.setId(rs.getInt(1));
            //    createPendingTasks(session, conn);
            //}

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * Utility that deletes the given a file.
     * 
     * @param file a File with an absolute path to delete.
     */
    private void delete(File file) {
        if (file.exists())
            file.delete();
    }


    public void addPendingTask(int sessionId, Task task) throws NonRecoverableException {
        final String sql = "INSERT INTO PendingTask (SessionId, TaskId, PendingStepId) VALUES (?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            conn.setAutoCommit(false);

            PendingStep pStep = new PendingStep(task.getCurrentStep());
            int pendingStepId = createPendingStep(sessionId, pStep, conn);

            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, sessionId);
            stmt.setInt(2, task.getId());
            stmt.setInt(3, pendingStepId);
            stmt.executeUpdate();

            conn.commit();

            System.out.println("addPendingTask inserted sessionId=" + sessionId);
            System.out.println("addPendingTask inserted taskId=" + task.getId());
            System.out.println("addPendingTask inserted pendingStepId=" + pendingStepId);

        } catch (SQLException e) {
            try {
                if (conn != null) conn.rollback();
            } catch (SQLException ignored) { }
            throw new NonRecoverableException("SessionDAO-ERR-ADD-PENDING-TASK", e);
        } finally {
            try {
                if (conn != null) conn.setAutoCommit(true);
            } catch (SQLException ignored) { }
            close(stmt);
            close(conn);
        }
    }
    
    private void createPendingTasks(TutoringSession session, Connection conn)
            throws NonRecoverableException {
        
        final String sql = "INSERT INTO PendingTask (SessionId, TaskId, PendingStepId) VALUES (?,?,?)";

        int sessionId = session.getId();

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            for (PendingTask pTask : session.getTasks()) {
                stmt.setInt(1, sessionId);
                stmt.setInt(2, pTask.getTask().getId());
                PendingStep pStep = pTask.currentStep();

                int pId = createPendingStep(sessionId, pStep, conn);
                stmt.setInt(3, pId);

                stmt.executeUpdate();

            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-7", e);
        } finally {
            System.out.println("createPendingTasks sessionId=" + session.getId());
            System.out.println("createPendingTasks taskCount=" + session.getTasks().size());
            close(stmt);
        }
    }

    private int createPendingStep(int sessionId, PendingStep pStep, Connection conn)
            throws NonRecoverableException {
        
        final String sql =
                "INSERT INTO PendingStep " +
                "(SessionId, StepId, NotifyTutor, IsCompleted, CurrentHintIndex) " +
                "VALUES (?,?,?,?,?)";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setInt(1, sessionId);
            stmt.setInt(2, pStep.getStep().getId());
            stmt.setBoolean(3, pStep.isNotifyTutor());
            stmt.setBoolean(4, pStep.isCompleted());
            stmt.setInt(5, pStep.getCurrentHintIndex());

            stmt.executeUpdate();

            ResultSet rs = stmt.getGeneratedKeys();

            if (rs.next()) {
                int pId = rs.getInt(1);
                pStep.setId(pId);
                return pId;
            } else {
                throw new NonRecoverableException("SessionDAO-ERR-8: PendingStep AutoIncrement Failed");
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-9", e);
        } finally {
            close(stmt);
        }
    }

    private ArrayList<PendingTask> retrievePendingTasks(TutoringSession session, Connection conn)
            throws NonRecoverableException {

        final String sql = "SELECT TaskId, PendingStepId FROM PendingTask WHERE SessionId = ?";

        ArrayList<PendingTask> pendingTasks = new ArrayList<>();

        PreparedStatement stmt = null;

        int sessionId = session.getId();

        int taskId = -1;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, sessionId);

            System.out.println("=== retrievePendingTasks START ===");
            System.out.println("sessionId=" + sessionId);
            System.out.println("problem=" + (session.getProblem() != null ? session.getProblem().getTitle() : "NULL"));

            ResultSet rs = stmt.executeQuery();

            int rowCount = 0;

            while (rs.next()) {
                rowCount++;

                taskId = rs.getInt("TaskId");

                System.out.println("retrieved pending taskId=" + taskId);
                System.out.println("retrieved pending stepId=" + rs.getInt("PendingStepId"));

                Task task = session.getProblem().findTaskById(taskId);

                PendingTask pTask = new PendingTask(task);

                PendingStep pStep = retrievePendingStep(rs.getInt("PendingStepId"), sessionId, task, conn);

                pTask.setCurrentStep(pStep);

                pendingTasks.add(pTask);
            }

            System.out.println("total pending rows found=" + rowCount);
            System.out.println("=== retrievePendingTasks END ===");

            return pendingTasks;

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-11", e);
        } finally {
            close(stmt);
        }
    }

    public PendingStep retrievePendingStep(int pendingStepId, int sessionId, Task task, Connection conn)
            throws NonRecoverableException {

        final String sql = "SELECT StepId, NotifyTutor, IsCompleted, CurrentHintIndex " +
                           "FROM PendingStep WHERE Id = ?";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, pendingStepId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                PendingStep pStep = new PendingStep(task.findStepById(rs.getInt(1)));

                pStep.setNotifyTutor(rs.getBoolean(2));
                pStep.setIsCompleted(rs.getBoolean(3));

                return pStep;
            } else {
                String errMsg = "PendingStep not found in pending task" + pendingStepId;
                throw new NonRecoverableException("SessionDAO-ERR-12", new InconsistentDBException(errMsg));
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-13", e);
        } finally {
            close(stmt);
        }
    }



/**
 * Remove a pending task (and its associated pending step) for a session.
 * 
 *
 * @param sessionId the tutoring session id
 * @param taskId the task id to remove
 * @throws NonRecoverableException on SQL errors
 */
public void deletePendingTask(int sessionId, int taskId) throws NonRecoverableException {
    final String selectSql = "SELECT PendingStepId FROM PendingTask WHERE SessionId = ? AND TaskId = ?";
    final String deleteTaskSql = "DELETE FROM PendingTask WHERE SessionId = ? AND TaskId = ?";
    final String deleteStepSql = "DELETE FROM PendingStep WHERE Id = ?";

    Connection conn = null;
    PreparedStatement selectStmt = null;
    PreparedStatement deleteTaskStmt = null;
    PreparedStatement deleteStepStmt = null;

    try {
        conn = DriverManager.getConnection(URL);
        conn.setAutoCommit(false);

        Integer pendingStepId = null;
        selectStmt = conn.prepareStatement(selectSql);
        selectStmt.setInt(1, sessionId);
        selectStmt.setInt(2, taskId);

        ResultSet rs = selectStmt.executeQuery();
        if (rs.next()) {
            pendingStepId = rs.getInt(1);
        }

        deleteTaskStmt = conn.prepareStatement(deleteTaskSql);
        deleteTaskStmt.setInt(1, sessionId);
        deleteTaskStmt.setInt(2, taskId);
        deleteTaskStmt.executeUpdate();

        if (pendingStepId != null) {
            deleteStepStmt = conn.prepareStatement(deleteStepSql);
            deleteStepStmt.setInt(1, pendingStepId);
            deleteStepStmt.executeUpdate();
        }

        conn.commit();
    } catch (SQLException e) {
        try {
            if (conn != null) conn.rollback();
        } catch (SQLException ignored) { }
        throw new NonRecoverableException("SessionDAO-ERR-DELETE-PENDING", e);
    } finally {
        try { if (conn != null) conn.setAutoCommit(true); } catch (SQLException ignored) { }
        close(selectStmt);
        close(deleteTaskStmt);
        close(deleteStepStmt);
        close(conn);
    }
}

    /**
     * Update the current pending task for this session with a new task/step.
     *
     * @param sessionId the tutoring session id
     * @param oldTaskId the task id currently pending (e.g., Welcome)
     * @param newTaskId the next task id to become pending (e.g., ASCII_ENCODE)
     * @param newStepId the step id to associate with the pending step (must exist in Step table)
     */
    public void updatePendingTask(int sessionId, int oldTaskId, int newTaskId, int newStepId) throws NonRecoverableException {
        final String selectSql = "SELECT PendingStepId FROM PendingTask WHERE SessionId = ? AND TaskId = ?";
        final String updateTaskSql = "UPDATE PendingTask SET TaskId = ? WHERE SessionId = ? AND TaskId = ?";
        final String updateStepSql = "UPDATE PendingStep SET StepId = ?, NotifyTutor = ?, IsCompleted = ?, CurrentHintIndex = ? WHERE Id = ?";

        Connection conn = null;
        PreparedStatement selectStmt = null;
        PreparedStatement updateTaskStmt = null;
        PreparedStatement updateStepStmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            conn.setAutoCommit(false);

            Integer pendingStepId = null;
            selectStmt = conn.prepareStatement(selectSql);
            selectStmt.setInt(1, sessionId);
            selectStmt.setInt(2, oldTaskId);

            ResultSet rs = selectStmt.executeQuery();
            if (rs.next()) {
                pendingStepId = rs.getInt(1);
            }

            // Update the task id first
            updateTaskStmt = conn.prepareStatement(updateTaskSql);
            updateTaskStmt.setInt(1, newTaskId);
            updateTaskStmt.setInt(2, sessionId);
            updateTaskStmt.setInt(3, oldTaskId);
            updateTaskStmt.executeUpdate();

            // Re-point the pending step at the new step id and reset its state
            if (pendingStepId != null) {
                updateStepStmt = conn.prepareStatement(updateStepSql);
                updateStepStmt.setInt(1, newStepId);
                updateStepStmt.setBoolean(2, true);
                updateStepStmt.setBoolean(3, false);
                updateStepStmt.setInt(4, 0);
                updateStepStmt.setInt(5, pendingStepId);
                updateStepStmt.executeUpdate();
            }

            conn.commit();
        } catch (SQLException e) {
            try { if (conn != null) conn.rollback(); } catch (SQLException ignored) {}
            throw new NonRecoverableException("SessionDAO-ERR-UPDATE-PENDING", e);
        } finally {
            try { if (conn != null) conn.setAutoCommit(true); } catch (SQLException ignored) {}
            close(selectStmt);
            close(updateTaskStmt);
            close(updateStepStmt);
            close(conn);
        }
    }

}
