package edu.regis.shatu.objectives;

import edu.regis.shatu.model.KnowledgeComponentKind;
import edu.regis.shatu.model.StepCompletion;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.aol.ProblemType;
import edu.regis.shatu.model.aol.StepSubType;
import edu.regis.shatu.model.steps.AddOneStep;
import edu.regis.shatu.svc.TutorReply;

public class AddOne extends Objective {
    public AddOne(Student student) {
        super(student);
    }

    @Override
    public TutorReply hint(StepCompletion completion) {
        return genericHint(completion, KnowledgeComponentKind.ADD_ONE_BIT,
                "Add a single '1' bit to the end of the message");
    }

    /**
     * Handles client requests for a new add one bit example.
     *
     * @return a TutorReply
     */
    @Override
    public TutorReply example(TutoringSession session, String jsonData) {

        System.out.println("Start tutor newaddonebitexample"); // Error checking

        AddOneStep newAddOneBit = gson.fromJson(jsonData, AddOneStep.class); // This is the AddOneStep created in the
                                                                             // newExample function from the AddOneView.

        int messageLength = newAddOneBit.getMessageLength(); // Set in the newExample function from the AddOneView,
                                                             // represents the String length that will be generated for
                                                             // the question.

        String question = generateRandomString(messageLength); // Generates a random string to convert to binary

        newAddOneBit.setQuestion(question);

        newAddOneBit.setResult(addOneFunction(question)); // Generates the binary version of the question, which is now
                                                          // the answer

        System.out.println(newAddOneBit.getResult()); // Error checking

        return genericExample(newAddOneBit, StepSubType.ADD_ONE_BIT, ProblemType.ADD_ONE_BIT,
                KnowledgeComponentKind.ADD_ONE_BIT,
                "Add one bit to the given bit string");
    }

    /**
     * This method is called from the AddOneView when the check button is
     * clicked, will check the users answer to the correct answer generated by
     * the newAddOneStep method in this file.
     * TODO: Refactor so that:
     * 1.) Steps in the database are actually completed since as of now, none exist
     * 2.) Steps are completed for Tasks (Task table) in Units (Unit Table)
     * 3.) Steps are completed for each Unit (See One, Do One, Teach One)
     * As of now, this is only logging assessment data (Assessment table) to the
     * database based on the number of
     * exposures, successes, and hints the user has completed during the Do One
     * section of the application and it is
     * not actually logging anything
     *
     * @param completion
     *
     * @return
     */
    @Override
    public TutorReply completeStep(StepCompletion completion) {

        AddOneStep completedStep = gson.fromJson(completion.getData(), AddOneStep.class);

        String userAnswer = String.valueOf(completedStep.getMessageLength());
        
        String correctAnswer = completedStep.getResult();

        System.out.println("Correct Answer: " + correctAnswer); // Error checking
        System.out.println("User Answer: " + userAnswer); // Error checking

        return genericComplete(correctAnswer, userAnswer, KnowledgeComponentKind.ADD_ONE_BIT);
    }

    /**
     * This method takes the question from the newAddOneStep ad converts it to
     * binary and returns the binary answer.
     *
     * @param question
     *
     * @return
     */
    private String addOneFunction(String question) {
        String answer;

        char stringArray[] = question.toCharArray();

        StringBuilder binary = new StringBuilder();

        for (int i = 0; i < stringArray.length; i++) {
            String binaryChar = String.format("%8s", Integer.toBinaryString(stringArray[i])).replaceAll(" ", "0");

            binary.append(binaryChar).append(" ");
        }

        answer = binary + "1";

        return answer;
    }

}