package edu.regis.shatu.objectives;

import edu.regis.shatu.err.NonRecoverableException;
import edu.regis.shatu.model.KnowledgeComponentKind;
import edu.regis.shatu.model.Pad0Step;
import edu.regis.shatu.model.Step;
import edu.regis.shatu.model.StepCompletion;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.StudentModelFieldKind;
import edu.regis.shatu.model.Task;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.aol.Assessment;
import edu.regis.shatu.model.aol.PendingStep;
import edu.regis.shatu.model.aol.PendingTask;
import edu.regis.shatu.model.aol.ProblemType;
import edu.regis.shatu.model.aol.StepSubType;
import edu.regis.shatu.model.aol.TaskKind;
import edu.regis.shatu.model.aol.Timeout;
import edu.regis.shatu.svc.ServiceFactory;
import edu.regis.shatu.svc.StudentModelSvc;
import edu.regis.shatu.svc.TutorReply;

public class PadZeros extends Objective {
    public PadZeros(Student student) {
        super(student);
    }

    @Override
    public TutorReply hint(StepCompletion completion) {
        return simpleHint(completion, KnowledgeComponentKind.PAD_ZEROS,
                "Add '0' bits until the message length is 448 mod 512");
    }

    /**
     * Handles client requests for a new pad with zeros example.
     *
     * @return a TutorReply
     */
    @Override
    public TutorReply example(TutoringSession session, String jsonData) {
        System.out.println("Start tutor newPadZerosExample"); // Error checking

        Pad0Step subStep = gson.fromJson(jsonData, Pad0Step.class);

        int messageLength = subStep.getMessageLength();

        String question = generateRandomString(messageLength);

        subStep.setQuestion(question);

        subStep.setResult(Integer.toString(calculateZerosNeededForPadding(messageLength))); // Calculates the number of
                                                                                            // zeros needed to pad the
                                                                                            // message correctly

        System.out.println(subStep.getResult()); // Error checking

        Step step = new Step(1, 0, StepSubType.PAD_ZEROS);

        // ToDo: fix timeouts
        Timeout timeout = new Timeout("Complete Step", 0, ":No-Op", "Exceed time");
        step.setTimeout(timeout);

        step.setData(gson.toJson(subStep));

        Task task = new Task();
        task.setKind(TaskKind.PROBLEM);
        task.setType(ProblemType.PAD_ZEROS);
        task.setDescription("Calculate zeros needed to pad the message");
        task.addStep(step);

        // Update the assessment data and save it to the database.
        int dbId = KnowledgeComponentKind.fromString("Pad with Zeros").dbId();
        Assessment assessment = studentModel.findAssessment(dbId);
        assessment.incrementExposures();

        try {
            StudentModelSvc modelSvc = ServiceFactory.findStudentModelSvc();
            modelSvc.updateAssessment(studentModel, assessment, StudentModelFieldKind.ATTEMPTS);

            PendingStep pendingStep = new PendingStep(step);
            pendingStep.setCurrentHintIndex(0);
            pendingStep.setNotifyTutor(true);
            pendingStep.setIsCompleted(false);

            PendingTask pendingTask = new PendingTask(task);
            pendingTask.setCurrentStep(pendingStep);

            TutorReply reply = new TutorReply(":Success");
            reply.setData(gson.toJson(pendingTask));

            return reply;

        } catch (NonRecoverableException ex) {
            return createError("Unknown error", ex);
        }
    }

    /**
     * This method is called from the Pad0View when the check button is clicked,
     * will check the users answer to the correct answer generated by the
     * newPad0Step method in this file.
     *
     * @param completion
     *
     * @return
     */
    @Override
    public TutorReply completeStep(StepCompletion completion) {

        Pad0Step completedPadZeroStep = gson.fromJson(completion.getData(), Pad0Step.class);

        String userAnswer = completedPadZeroStep.getUserAnswer();
        String correctAnswer = completedPadZeroStep.getResult();

        System.out.println("user answer: " + userAnswer); // Error checking
        System.out.println("Correct answer: " + correctAnswer); // Error checking

        return genericComplete(correctAnswer, userAnswer, KnowledgeComponentKind.PAD_ZEROS);
    }

    /**
     * This function is called from the newPadZeroStep method and will calculate
     * the zeros needed for the SHA256 message. The variables are written
     * purposely to give the developer a easier understanding of whats being
     * calculated instead of just using the integers.
     *
     * @param messageLength
     *
     * @return
     */
    private int calculateZerosNeededForPadding(int messageLength) {
        int sha256MessageLength = 512;
        int messageLengthStepBitsNeeded = 64;
        int padZerosStepBitsLength = sha256MessageLength - messageLengthStepBitsNeeded;
        int bitsPerCharacter = 8;
        int totalBitsPerMessage = bitsPerCharacter * messageLength;
        int appendOneBit = 1;
        int totalMessageLengthInBits = totalBitsPerMessage + appendOneBit;
        int zerosNeededToPadMessage = padZerosStepBitsLength - totalMessageLengthInBits;

        return zerosNeededToPadMessage;
    }
}
