package edu.regis.shatu.objectives;

import edu.regis.shatu.err.NonRecoverableException;
import edu.regis.shatu.model.KnowledgeComponentKind;
import edu.regis.shatu.model.Pad0Step;
import edu.regis.shatu.model.Step;
import edu.regis.shatu.model.StepCompletion;
import edu.regis.shatu.model.StepCompletionReply;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.StudentModelFieldKind;
import edu.regis.shatu.model.Task;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.aol.Assessment;
import edu.regis.shatu.model.aol.PendingStep;
import edu.regis.shatu.model.aol.PendingTask;
import edu.regis.shatu.model.aol.ProblemType;
import edu.regis.shatu.model.aol.StepSubType;
import edu.regis.shatu.model.aol.TaskKind;
import edu.regis.shatu.model.aol.Timeout;
import edu.regis.shatu.svc.ServiceFactory;
import edu.regis.shatu.svc.StudentModelSvc;
import edu.regis.shatu.svc.TutorReply;

public class PadZeros extends Objective {
    public PadZeros(Student student) {
        super(student);
    }

    @Override
    public TutorReply hint(StepCompletion completion) {
        return simpleHint(completion, "Pad with Zeros", "Add '0' bits until the message length is 448 mod 512");
    }

    /**
     * Handles client requests for a new pad with zeros example.
     *
     * @return a TutorReply
     */
    @Override
    public TutorReply example(TutoringSession session, String jsonData) {
        System.out.println("Start tutor newPadZerosExample"); // Error checking

        Pad0Step subStep = gson.fromJson(jsonData, Pad0Step.class);

        int messageLength = subStep.getMessageLength();

        String question = generateRandomString(messageLength);

        subStep.setQuestion(question);

        subStep.setResult(Integer.toString(calculateZerosNeededForPadding(messageLength))); // Calculates the number of
                                                                                            // zeros needed to pad the
                                                                                            // message correctly

        System.out.println(subStep.getResult()); // Error checking

        Step step = new Step(1, 0, StepSubType.PAD_ZEROS);

        // ToDo: fix timeouts
        Timeout timeout = new Timeout("Complete Step", 0, ":No-Op", "Exceed time");
        step.setTimeout(timeout);

        step.setData(gson.toJson(subStep));

        Task task = new Task();
        task.setKind(TaskKind.PROBLEM);
        task.setType(ProblemType.PAD_ZEROS);
        task.setDescription("Calculate zeros needed to pad the message");
        task.addStep(step);

        // Update the assessment data and save it to the database.
        int dbId = KnowledgeComponentKind.fromString("Pad with Zeros").dbId();
        Assessment assessment = studentModel.findAssessment(dbId);
        assessment.incrementExposures();

        try {
            StudentModelSvc modelSvc = ServiceFactory.findStudentModelSvc();
            modelSvc.updateAssessment(studentModel, assessment, StudentModelFieldKind.ATTEMPTS);

            PendingStep pendingStep = new PendingStep(step);
            pendingStep.setCurrentHintIndex(0);
            pendingStep.setNotifyTutor(true);
            pendingStep.setIsCompleted(false);

            PendingTask pendingTask = new PendingTask(task);
            pendingTask.setCurrentStep(pendingStep);

            TutorReply reply = new TutorReply(":Success");
            reply.setData(gson.toJson(pendingTask));

            return reply;

        } catch (NonRecoverableException ex) {
            return createError("Unknown error", ex);
        }
    }

    /**
     * This method is called from the Pad0View when the check button is clicked,
     * will check the users answer to the correct answer generated by the
     * newPad0Step method in this file.
     *
     * @param completion
     *
     * @return
     */
    @Override
    public TutorReply completeStep(StepCompletion completion) {

        Pad0Step completedPadZeroStep = gson.fromJson(completion.getData(), Pad0Step.class);

        String userAnswer = completedPadZeroStep.getUserAnswer();
        String correctAnswer = completedPadZeroStep.getResult();

        System.out.println("user answer: " + userAnswer); // Error checking
        System.out.println("Correct answer: " + correctAnswer); // Error checking

        StepCompletionReply stepReply = new StepCompletionReply();
        stepReply.setCorrectAnswer(correctAnswer);
        stepReply.setResponse(userAnswer);

        if (userAnswer.equals(correctAnswer)) { // User was correct
            System.out.println("Answer was correct, correct if branch taken."); // Error checking
            stepReply.setIsCorrect(true);
            stepReply.setIsRepeatStep(false);
            stepReply.setIsNewStep(true);

            // ToDo: Use the student model to figure out whether we want
            // to give the student another practice problem of the same
            // type or move on to an entirely different problem.
            stepReply.setIsNewTask(true);

            // ToDo: currently only one step in a task, so there isn't a next one???
            stepReply.setIsNextStep(false);

            // Update the assessment data and save it to the database.
            int dbId = KnowledgeComponentKind.fromString("Pad with Zeros").dbId();
            Assessment assessment = studentModel.findAssessment(dbId);
            assessment.incrementSuccessess();

            try {
                StudentModelSvc modelSvc = ServiceFactory.findStudentModelSvc();
                modelSvc.updateAssessment(studentModel, assessment, StudentModelFieldKind.SUCCESSES);

            } catch (NonRecoverableException ex) {
                return createError("Unknown error", ex);
            }

            int exposures = assessment.getExposures();
            int successes = assessment.getSuccessess();

            if (exposures > 0 && (double) successes / exposures > 0.6) {
                stepReply.setIsNewTask(true);
                System.out.println("%%%%%%%%%%% Next Task Recommended");
            } else {
                stepReply.setIsNewTask(false);
            }

        } else { // User was wrong
            System.out.println("Answer was not correct, correct if branch taken."); // Error checking
            stepReply.setIsCorrect(false);
            stepReply.setIsRepeatStep(true);
            stepReply.setIsNewStep(false);
            stepReply.setIsNewTask(false);
            stepReply.setIsNextStep(false);
        }

        Step step = new Step(1, 0, StepSubType.STEP_COMPLETION_REPLY);

        // ToDo: fix timeouts
        Timeout timeout = new Timeout("Complete Step", 0, ":No-Op", "Exceed time");
        step.setTimeout(timeout);
        step.setData(gson.toJson(stepReply));

        Task task = new Task();
        task.setKind(TaskKind.PROBLEM);
        task.setType(ProblemType.STEP_COMPLETION_REPLY);
        task.setDescription("Choose your next action");
        task.addStep(step);

        PendingStep pendingStep = new PendingStep(step);
        pendingStep.setCurrentHintIndex(0);
        pendingStep.setNotifyTutor(true);
        pendingStep.setIsCompleted(false);

        PendingTask pendingTask = new PendingTask(task);
        pendingTask.setCurrentStep(pendingStep);

        TutorReply reply = new TutorReply(":Success");

        reply.setData(gson.toJson(pendingTask));

        return reply;
    }

    /**
     * This function is called from the newPadZeroStep method and will calculate
     * the zeros needed for the SHA256 message. The variables are written
     * purposely to give the developer a easier understanding of whats being
     * calculated instead of just using the integers.
     *
     * @param messageLength
     *
     * @return
     */
    private int calculateZerosNeededForPadding(int messageLength) {
        int sha256MessageLength = 512;
        int messageLengthStepBitsNeeded = 64;
        int padZerosStepBitsLength = sha256MessageLength - messageLengthStepBitsNeeded;
        int bitsPerCharacter = 8;
        int totalBitsPerMessage = bitsPerCharacter * messageLength;
        int appendOneBit = 1;
        int totalMessageLengthInBits = totalBitsPerMessage + appendOneBit;
        int zerosNeededToPadMessage = padZerosStepBitsLength - totalMessageLengthInBits;

        return zerosNeededToPadMessage;
    }
}
