package edu.regis.shatu.objectives;

import edu.regis.shatu.model.KnowledgeComponentKind;
import edu.regis.shatu.model.StepCompletion;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.aol.ProblemType;
import edu.regis.shatu.model.aol.StepSubType;
import edu.regis.shatu.model.steps.Pad0Step;
import edu.regis.shatu.svc.TutorReply;

public class PadZeros extends Objective {
    public PadZeros(Student student) {
        super(student);
    }

    @Override
    public TutorReply hint(StepCompletion completion) {
        return genericHint(completion, KnowledgeComponentKind.PAD_ZEROS,
                "Add '0' bits until the message length is 448 mod 512");
    }

    /**
     * Handles client requests for a new pad with zeros example.
     *
     * @return a TutorReply
     */
    @Override
    public TutorReply example(TutoringSession session, String jsonData) {
        System.out.println("Start tutor newPadZerosExample"); // Error checking

        Pad0Step subStep = gson.fromJson(jsonData, Pad0Step.class);

        int messageLength = subStep.getMessageLength();

        String question = generateRandomString(messageLength);

        subStep.setQuestion(question);

        subStep.setResult(Integer.toString(calculateZerosNeededForPadding(messageLength))); // Calculates the number of
                                                                                            // zeros needed to pad the
                                                                                            // message correctly

        System.out.println(subStep.getResult()); // Error checking

        return genericExample(subStep, StepSubType.PAD_ZEROS, ProblemType.PAD_ZEROS, KnowledgeComponentKind.PAD_ZEROS,
                "Calculate zeroes needed to pad the message");
    }

    /**
     * This method is called from the Pad0View when the check button is clicked,
     * will check the users answer to the correct answer generated by the
     * newPad0Step method in this file.
     * TODO: Refactor so that:
     * 1.) Steps in the database are actually completed since as of now, none exist
     * 2.) Steps are completed for Tasks (Task table) in Units (Unit Table)
     * 3.) Steps are completed for each Unit (See One, Do One, Teach One)
     * As of now, this is only logging assessment data (Assessment table) to the
     * database based on the number of
     * exposures, successes, and hints the user has completed during the Do One
     * section of the application and it is
     * not actually logging anything
     *
     * @param completion
     *
     * @return
     */
    @Override
    public TutorReply completeStep(StepCompletion completion) {

        Pad0Step completedPadZeroStep = gson.fromJson(completion.getData(), Pad0Step.class);

        String userAnswer = completedPadZeroStep.getUserAnswer();
        String correctAnswer = completedPadZeroStep.getResult();

        System.out.println("user answer: " + userAnswer); // Error checking
        System.out.println("Correct answer: " + correctAnswer); // Error checking

        return genericComplete(correctAnswer, userAnswer, KnowledgeComponentKind.PAD_ZEROS);
    }

    /**
     * This function is called from the newPadZeroStep method and will calculate
     * the zeros needed for the SHA256 message. The variables are written
     * purposely to give the developer a easier understanding of whats being
     * calculated instead of just using the integers.
     *
     * @param messageLength
     *
     * @return
     */
    private int calculateZerosNeededForPadding(int messageLength) {
        int sha256MessageLength = 512;
        int messageLengthStepBitsNeeded = 64;
        int padZerosStepBitsLength = sha256MessageLength - messageLengthStepBitsNeeded;
        int bitsPerCharacter = 8;
        int totalBitsPerMessage = bitsPerCharacter * messageLength;
        int appendOneBit = 1;
        int totalMessageLengthInBits = totalBitsPerMessage + appendOneBit;
        int zerosNeededToPadMessage = padZerosStepBitsLength - totalMessageLengthInBits;

        return zerosNeededToPadMessage;
    }
}