# SHATU: SHA-256 Tutor
# 
#  (C) Johanna & Richard Blumenthal, All rights reserved
# 
#  Unauthorized use, duplication or distribution without the authors'
#  permission is strictly prohibited.
# 
#  Unless required by applicable law or agreed to in writing, this
#  software is distributed on an "AS IS" basis without warranties
#  or conditions of any kind, either expressed or implied.

# Assigns the language displayed in the UI
language=en
#language=DE

# Assigns the locale language variant displayed in the UI
country=us
#country=DE

# The computer host on which the MySQL database executes (default: localhost).
edu.regis.shatu.DB_HOST=localhost

# The computer port on which the MySQL database executes (default: 3306)
edu.regis.shatu.DB_PORT=3306

# The name of the ShaTu database (default: ShaTuDB).
edu.regis.shatu.DB_NAME=ShaTuDB

# The user id ShaTu uses to log into the database (default: ShaTuTs).
edu.regis.shatu.DB_USER=ShaTuTs

# The password ShaTu uses to login to the database (default: ShTu2023).
edu.regis.shatu.DB_PASS=ShaTu2023