
package edu.regis.shatu.objectives;

import edu.regis.shatu.err.NonRecoverableException;
import edu.regis.shatu.model.Hint;
import edu.regis.shatu.model.KnowledgeComponentKind;
import edu.regis.shatu.model.StepCompletion;
import edu.regis.shatu.model.Student;
import edu.regis.shatu.model.StudentModelFieldKind;
import edu.regis.shatu.model.TutoringSession;
import edu.regis.shatu.model.aol.Assessment;
import edu.regis.shatu.model.aol.PendingStep;
import edu.regis.shatu.model.aol.ProblemType;
import edu.regis.shatu.model.aol.StepSubType;
import edu.regis.shatu.model.aol.Timeout;
import edu.regis.shatu.model.steps.EncodeAsciiStep;
import edu.regis.shatu.model.steps.Step;
import edu.regis.shatu.model.steps.StepCompletionReply;
import edu.regis.shatu.svc.ServiceFactory;
import edu.regis.shatu.svc.StudentModelSvc;
import edu.regis.shatu.svc.TutorReply;

public class EncodeAscii extends Objective {
    public EncodeAscii(Student student) {
        super(student);
    }

    @Override
    public TutorReply hint(StepCompletion completion) {
        System.out.println("Tutor hintEncode");

        StepCompletionReply stepReply = new StepCompletionReply();

        stepReply.setIsCorrect(false);
        stepReply.setIsRepeatStep(true);
        stepReply.setIsNewStep(false);
        stepReply.setIsNewTask(false);
        stepReply.setIsNextStep(false);

        Hint hintOne = new Hint();
        hintOne.setId(0);
        hintOne.setText("Convert each character to its ASCII value");

        Hint hintTwo = new Hint();
        hintTwo.setId(1);
        hintTwo.setText("Each character should be represented by 8 bits");

        Step step = completion.getStep();
        step.addHint(hintOne);
        step.addHint(hintTwo);

        step.setSubType(StepSubType.REQUEST_HINT);
        Timeout timeout = new Timeout("Complete Step", 0, ":No-Op", "Exceed time");
        step.setTimeout(timeout);
        step.setData(gson.toJson(stepReply));

        PendingStep pendingStep = new PendingStep(step);
        pendingStep.setCurrentHintIndex(0);
        pendingStep.setNotifyTutor(true);
        pendingStep.setIsCompleted(false);

        TutorReply reply = new TutorReply(":Success");
        reply.setData(gson.toJson(pendingStep));

        // Update the assessment data and save it to the database.
        int dbId = KnowledgeComponentKind.fromString("ASCII Encode").dbId();
        Assessment assessment = studentModel.findAssessment(dbId);
        assessment.incrementHints();

        try {
            StudentModelSvc modelSvc = ServiceFactory.findStudentModelSvc();
            modelSvc.updateAssessment(studentModel, assessment, StudentModelFieldKind.HINTS);

        } catch (NonRecoverableException ex) {
            return createError("Unknown error", ex);
        }

        return reply;
    }

    /**
     * Handles client requests for a new ASCII encode example.
     *
     * @return a TutorReply whose data contains a JSon EncodeAsciiExample
     *         object.
     */
    @Override
    public TutorReply example(TutoringSession session, String jsonData) {
        System.out.println("Start tutor newEncodeAsciiexample"); // Error checking

        EncodeAsciiStep newEncodeAscii = gson.fromJson(jsonData, EncodeAsciiStep.class);

        if (newEncodeAscii.getQuestion().isEmpty() || newEncodeAscii.getQuestion() == null) {

            System.out.println("Question was empty"); // Error checking

            int messageLength = newEncodeAscii.getMessageLength();

            String newQuestion = generateRandomString(messageLength); // Generates a random string to convert to binary

            newEncodeAscii.setQuestion(newQuestion);

            newEncodeAscii.setResult(toBinaryFunction(newQuestion));

        } else {
            newEncodeAscii.setResult(toBinaryFunction(newEncodeAscii.getQuestion()));
        }

        System.out.println(newEncodeAscii.getResult()); // Error checking

        return genericExample(newEncodeAscii, StepSubType.ENCODE_ASCII, ProblemType.ASCII_ENCODE,
                KnowledgeComponentKind.ASCII_ENCODE, "Convert the question to binary");
    }

    /**
     * This method is called from the EncodeAsciiView when the check button is
     * clicked, will check the users answer to the correct answer generated by
     * the newEncodeAsciiStep method in this file.
     * TODO: Refactor so that:
     * 1.) Steps in the database are actually completed since as of now, none exist
     * 2.) Steps are completed for Tasks (Task table) in Units (Unit Table)
     * 3.) Steps are completed for each Unit (See One, Do One, Teach One)
     * As of now, this is only logging assessment data (Assessment table) to the
     * database based on the number of
     * exposures, successes, and hints the user has completed during the Do One
     * section of the application and it is
     * not actually logging anything
     *
     * @param completion
     *
     * @return
     */
    @Override
    public TutorReply completeStep(StepCompletion completion) {
        // EncodeAsciiStep from the StepCompletion function in the Encode Ascii View
        EncodeAsciiStep completedEncodeAsciiStep = gson.fromJson(completion.getData(), EncodeAsciiStep.class);

        String studentAnswer = completedEncodeAsciiStep.getAscii(); // What the user submitted as the answer.
        String correctAnswer = completedEncodeAsciiStep.getResult();

        System.out.println("Correct Answer: " + correctAnswer); // Error checking
        System.out.println("User Answer: " + studentAnswer); // Error checking

        return genericComplete(correctAnswer, studentAnswer, KnowledgeComponentKind.ASCII_ENCODE);
    }

    /**
     * Function that can take a string and convert it to binary
     *
     * @param question
     * @return
     */
    private String toBinaryFunction(String question) {
        String answer;

        char stringArray[] = question.toCharArray();

        StringBuilder binary = new StringBuilder();

        for (int i = 0; i < stringArray.length; i++) {
            String binaryChar = String.format("%8s", Integer.toBinaryString(stringArray[i])).replaceAll(" ", "0");

            binary.append(binaryChar);
        }

        answer = binary.toString();

        return answer;
    }

}
